### ISSUE TITLE
Suggestion : Add option to automatically pick a random invidious instance

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#42]
I suggest to add an option wich can be disabled to automatically pick a random invidious instance (to avoid 500 error)
straw-viewer is using this option : 
https://github.com/trizen/straw-viewer/blob/master/README.md#invidious-instances

**Comment by lekma** [comment]
I'm not sure it is either practical nor useful (also, I don't really like the idea of choosing an instance without the user knowing)...

**Comment by DavidHenryThoreau** [comment]
This instance may be choosen between the list used in preferences.

**Comment by memartinb** [comment]
I like the idea, though I doubt it would be usable at the moment since few of the instances seem to be working reliably. I guess one would run into errors a lot. OTOH having an option in the settings (and having it turned off by default) wouldn't hurt.

Cheerz@lekma and a big thanks for bringing yt back to kodi ❤

**Comment by DavidHenryThoreau** [comment]
> I'm not sure it is either practical nor useful (also, I don't really like the idea of choosing an instance without the user knowing)...

Yeah, that's true but when some instances are overcharged, we need to go to preferences and change to another, test, and try another.. These could be automatically done by check a random instance.

**Comment by DJCrashdummy** [comment]
similar is done by [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect):
it uses a smaller subset of available lists (which can be edited by the user), so you don't have to change your instance every few days if something isn't working right now at your preferred **one** instance. ...so even users who only want to use one or very few trusted instances can just use their own very small list of servers and users who don't care stay with the default random list.
-> load balancing and failure prevention in one swoop. :wink:

**Comment by SethFalco** [comment]
I think this would be a very valuable feature. However, it'd be best to implement it slightly differently.

The issue, as-is, essentially load balances requests across instances, which can be nice to ensure no single instance gets overwhelmed. However, it's not a very practical when we know servers are scattered across the world, and so latency may vary widely. I'm also wary that there may be issues with consistency between instances, depending on how aggressively they cache video or channel info.

Instead, I'd like to see an option called "Auto".

It should ping each instance available, and choose one based on latency. There should be a map somewhere that temporarily backs off certain instances if they returned errors recently. Whenever this selection takes place, it will always notify the user of which server it switched to.

For example, given the list of instances:

* example.org (47 ms)
* example.com (23 ms)
* example.fun (120 ms)

It will use example.com.

If while using example.com, it runs into an error such as a timeout, forbidden, or some other error:

1. Add it to a map with a TTL, so we know not to use it again for a while.
2. Repeat the pings.
3. Pick the next best instance, so `example.org` in this case if each ping was the same.
4. Notify the user that an error occurred, and which instance the addon switched to.

It would be even better if it retried the request after, and switched again if necessary, until the action the user attempted to do succeeds.

**Comment by SethFalco** [comment]
I've been working on my proposed solution, and have found some flaws with it.

First, there isn't a platform-agnostic way to ping hosts with Python, and I don't think it's worth concerning over platform specifics or using a library.

To keep logic platform-agnostic, I tested an implementation where I did an HTTP request to the `/stats` endpoint of each instance to measure latency. However, the same instance can vary pretty widely, so they might as well all be overlapping. When many requests are performed, it's easy to average and determine the best server, but this approach is shoddy when comparing one-off requests. Plus, this was a bit messy anyway. 

You can see my WIP implementation here:
* https://github.com/SethFalco/plugin.video.invidious/commit/f14a3dc8b25379ae66682457ca1a8a5fb2698ad5

Meanwhile, I think the best approach for this is to scrap latency.

There would be a setting called **Auto-switch instances**.

If enabled, we continue to use the instance the user has configured. It also does not stop them from reconfiguring it whenever they want, or from using the server browser.

If enabled, whenever an error occurs, such as a timeout, rate limit, or internal server error, we add the current instance to a backoff list for 24-hours. Meanwhile, we switch to another instance and notify the user.

Since we don't have latency, the following strategy would be used to determine the next instance, ignoring instances still on the backoff list:

* Check if there are any other instances in the same region, and pick the one with the best uptime.
* If there aren't any others in the same region, just pick the one with the best uptime.

---

I'll update my branch to behave like the above tomorrow. :yawning_face:

**Comment by lekma** [comment]
@SethFalco: I'm still not convinced it is either practical or useful...

**Comment by SethFalco** [comment]
Ahh, I thought it'd be quite nice.
I'll give my use-case, but if you aren't a fan, then I'll set that PR aside for now to focus on other things. :+1:

I use Invidious on my TV (HTPC), and sometimes instances can be unreliable. Even larger instances like `y.com.sb`, `vid.puffyan.us`, and `inv.riverside.rocks` can be flaky, and I'm not sure why tbh. :thinking: 

A request failing occurs at least every other day, but is usually fine. It's just a retry away. However, around once every 1-2 weeks, it's bad enough that I have to flip between a few instances, which is a chore especially when watching with others.

Though the recent merge with getting regions shown in the menu is _very_ helpful, it'd be even better if the failures were effectively invisible, imo.

---

If the above doesn't seem like a worthwhile reason to you, I'd be happy to shelve this and explore other avenues.

For example:

Making is easier for users to identify the best instance for them, like the region change we did recently.

Make a shortcut or menu to users can switch instance faster, so it feels less cumbersome. For example, maybe we can add the `selectInstance` script/action here on the left:

![image](https://github.com/lekma/plugin.video.invidious/assets/22801583/ec40ce87-94d5-4c4b-9d89-31478fba0f70)
> What a user sees when they press `←`` on their controller while in the addon menus.

I could also try to familiarize myself more with upstream, to take a deeper look at I/O errors and performance to improve stability. A bit intimidating, but the most favorable action anyway. ^-^'

**Comment by lekma** [comment]
given the state of public instances right now, i think this is a lost cause, but if someone wants to tackle it...
